/* tslint:disable */
/* eslint-disable */
/**
 * Consulting Form API
 * Handles submission of consultation forms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xtodorovic@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsultingForm
 */
export interface ConsultingForm {
    /**
     * 
     * @type {string}
     * @memberof ConsultingForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ConsultingForm
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ConsultingForm
     */
    symptoms: string;
}

/**
 * Check if a given object implements the ConsultingForm interface.
 */
export function instanceOfConsultingForm(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "symptoms" in value;

    return isInstance;
}

export function ConsultingFormFromJSON(json: any): ConsultingForm {
    return ConsultingFormFromJSONTyped(json, false);
}

export function ConsultingFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsultingForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'symptoms': json['symptoms'],
    };
}

export function ConsultingFormToJSON(value?: ConsultingForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'symptoms': value.symptoms,
    };
}

