/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Consulting List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xtodorovic@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsultationUpdate
 */
export interface ConsultationUpdate {
    /**
     * Unique identifier of the consultation request
     * @type {string}
     * @memberof ConsultationUpdate
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ConsultationUpdate
     */
    scheduledDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ConsultationUpdate
     */
    scheduledTime: string;
    /**
     * 
     * @type {string}
     * @memberof ConsultationUpdate
     */
    videoLink: string;
}

/**
 * Check if a given object implements the ConsultationUpdate interface.
 */
export function instanceOfConsultationUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "scheduledDate" in value;
    isInstance = isInstance && "scheduledTime" in value;
    isInstance = isInstance && "videoLink" in value;

    return isInstance;
}

export function ConsultationUpdateFromJSON(json: any): ConsultationUpdate {
    return ConsultationUpdateFromJSONTyped(json, false);
}

export function ConsultationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsultationUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scheduledDate': (new Date(json['scheduledDate'])),
        'scheduledTime': json['scheduledTime'],
        'videoLink': json['videoLink'],
    };
}

export function ConsultationUpdateToJSON(value?: ConsultationUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scheduledDate': (value.scheduledDate.toISOString().substr(0,10)),
        'scheduledTime': value.scheduledTime,
        'videoLink': value.videoLink,
    };
}

